#!/usr/bin/env bash
#comentario
IFS=':'
while read -r US PSS U_ID G_ID USINF HDIR CSHL
do
    echo "The user $US is part of the $G_ID gang, lives in $HDIR and rides $CSHL. $U_ID's place is protected by the passcode $PSS, more info about the user here: $USINF"
done < /etc/passwd
